<?php

namespace App\Models\Social\Socialable\Vkontakte;

use App\Models\Social\Socialable\BaseClient;
use App\Services\Social\VkontakteSocialService;
use Exception;

class VkontakteUser extends BaseClient
{
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (VkontakteUser $user) {
            return $user->setClientInfo();
        });
    }

    /**
     * @return bool
     * @throws Exception
     */
    public function setClientInfo(): bool
    {
        $service = new VkontakteSocialService();

        return $service->setClientInfo($this);
    }
}
